### ISSUE TITLE
Beautify the application and support Multiple pairs 

### ISSUE THREAD

**Issue by GrandGarcon** [GoodDollarCommons/StakeGoodDollar#1]
## Context 

By allowing  the support of Uniswap fetching of tokenlists , there can be immense possiblities of providing liquidity to the project . allowing to swap the tokens present in the list to  DAI / G$  and then staking provides  much better exchange rate .

## Possible way of implementation :
-  fetch from the based on the token schema format [in the link](https://uniswap.org/tokenlist.schema.json).
-  then  also  doing minimalistic changes to make the UI to default ( like of uniswap) and display  the tokenlist to be chosen as the dropdown list in the box.

**Comment by bertux** [comment]
this is for next version of TradeGoodDollar which will be in future GoodSwap repository based on create-eth-app template generator and not for StakeGoodDollar so i let you recreate it in TradeGoodDollar for history.
